#!/usr/bin/env python3
"""Generate three structural smoke-test files from the current Backend source tree."""

import ast
from pathlib import Path


ROOT = Path(__file__).resolve().parent
BACKEND = ROOT / "Backend"
OUTPUTS = {
    "backend": ROOT / "tests" / "test_generated_backend.py",
    "terminal_assistant": ROOT / "tests" / "test_generated_terminal_assistant.py",
    "terminal_workflow": ROOT / "tests" / "test_generated_terminal_workflow.py",
}


# Convert a source path such as Backend/routes/auth_routes.py into its import name.
def module_name(path: Path) -> str:
    return ".".join(path.relative_to(ROOT).with_suffix("").parts)


# Read top-level functions and classes so the generated test can verify module structure.
def defined_symbols(path: Path) -> list[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    node_types = (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)
    return sorted(node.name for node in tree.body if isinstance(node, node_types))


# Render one unittest module that imports every source module in its assigned group.
def render(title: str, paths: list[Path]) -> str:
    modules = [module_name(path) for path in paths]
    symbols = {module_name(path): defined_symbols(path) for path in paths}
    class_name = "".join(part.title() for part in title.split("_")) + "GeneratedTests"
    return f'''"""AUTO-GENERATED by generate-tests.py; do not edit this file manually."""

import importlib
import unittest


MODULES = {modules!r}
SYMBOLS = {symbols!r}


class {class_name}(unittest.TestCase):
    # Verify that every discovered module imports without a syntax or startup error.
    def test_modules_import(self):
        for name in MODULES:
            with self.subTest(module=name):
                importlib.import_module(name)

    # Verify that each top-level function or class remains available after import.
    def test_defined_symbols_are_available(self):
        for name, expected in SYMBOLS.items():
            module = importlib.import_module(name)
            for symbol in expected:
                with self.subTest(module=name, symbol=symbol):
                    self.assertTrue(hasattr(module, symbol))
'''


# Group source files, regenerate all three tests, and report their paths.
def main() -> None:
    paths = sorted(BACKEND.rglob("*.py"))
    assistant = [path for path in paths if "terminal_assistant" in path.parts]
    workflow_names = {"cli.py", "split_terminal.py", "terminal_workflow.py"}
    workflow = [path for path in paths if path.name in workflow_names]
    backend = [path for path in paths if path not in assistant and path not in workflow]
    for title, group in {
        "backend": backend,
        "terminal_assistant": assistant,
        "terminal_workflow": workflow,
    }.items():
        OUTPUTS[title].write_text(render(title, group), encoding="utf-8")
        print(f"Generated {OUTPUTS[title].relative_to(ROOT)}")


if __name__ == "__main__":
    main()
